core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

This is a new feature for "GROUP BY ROLLUP", which we do not support yet. The changes belongs to the same.

Rav 842 macy sprint4 null pointer exception cannot get property 'expression type' on null object

---

core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java
core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
core/src/main/java/org/apache/calcite/sql/validate/SqlConformanceEnum.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

2. Changed SqlConformance.allowsGroupByAlias() to include BigQuery.

1. GroupBy Alias Support in RelToSqlConverter.

---

core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java

**Problem:**
Right now if we simply say 
`select null from employee`
then calcite prints
`select cast(null as null) from employee`
in the above case we need not cast `NULL`. 
**Fix:**
If the target type is non null then only we'll cast `NULL` to target else don't.

"Cast null as null" fix

---

core/src/main/java/org/apache/calcite/sql/SqlIntervalQualifier.java

**Details:**
In a scenario where we serialize the database schema information, we serialize calcite data types / sql node and use it later in subsequent steps. In order to achieve the serialization we need `SqlIntervalQualifier` to be serialized.
**Implementation Details:**
`SqlIntervalQualifier` is now implementing the `Serializable` interface.
**Jira:**
https://datametica.atlassian.net/browse/EEF-2972

allowing serialization for SqlIntervalQualifier class

---

core/src/main/java/org/apache/calcite/sql/SqlIntervalQualifier.java
core/src/main/java/org/apache/calcite/sql/SqlNode.java

Details:
In a scenario where we serialize the database schema information, we serialize calcite data types / sql node and use it later in subsequent steps. In order to achieve the serialization we need `SqlNode` to be serialized.
Implementation Details:
`SqlNode` is now implementing the Serializable interface.
Jira:
https://datametica.atlassian.net/browse/EEF-2972

allowing serialization for SqlNode class

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java

Added a switch case for character_length function so that it is printed as LENGTH in BQ

CHARACTER_LENGTH() printed as LENGTH() in BQ

---

core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

- Support for [Position function](https://spark.apache.org/docs/latest/api/sql/index.html#position)
- Support for [Trim function](https://spark.apache.org/docs/latest/api/sql/#trim)
- Support for [Concat Pipe operator](https://docs.databricks.com/spark/latest/spark-sql/language-manual/functions/pipepipesign.html)
- Latest [Datetime patterns](https://spark.apache.org/docs/latest/sql-ref-datetime-pattern.html) 
- Reverted back addition of date +- interval DAY(before it was data_add, date_sub), date +- interval month(add_months) to binary operators as QA wants it  that way.

Support for TRIM, POSITION, CONCAT pipe operator, RAISE_ERROR in spark.

---

core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Removing emulation of null direction in spark.
Support for [null direction](https://docs.databricks.com/spark/latest/spark-sql/language-manual/sql-ref-syntax-qry-select-sortby.html) in spark.

Emulation of null direction in spark

---

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Added support to create a subquery if the In-clause subquery has function call in group by clause. 
In case of In-subquery with group by and having clause , alias generated by raven for the function call was not getting resolved.

RNBS-264-adds-subquery-support-for-In-Clause-having-functioncall-in-groupBy

---

core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/main/java/org/apache/calcite/util/CastCallBuilder.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

As Spark does not have a Time Datatype Time is converted to TimeStamp with a default date of 1970-01-01

Spark Time to Timestamp cast

---

core/src/main/java/org/apache/calcite/tools/Frameworks.java

[CALCITE-4760] RelBuilder creation fails with error 'No suitable driver found for jdbc:calcite:' in shaded Calcite Issues caused by jar-packaging/shading.
https://github.com/julianhyde/calcite/commit/2b830d80f6e4ac9b0efeead7c0542be2fdfd573d

Fix for- No suitable driver found for jdbc:calcite

---

core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

adds support to keep where clause as-is if analytic function is used in filter rel and the input node of filter rel is a logical join.

RNBS-1210-adds-support-to-keep-where-clause-as-is-if-analytic-function-is-used-in-filter-rel

---

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Aggregate Call with collation is translated to WITHIN_GROUP during Rel To Sql Conversion. i.e.,
LIST_AGG("first_name", ": ") WITHIN_GROUP (ORDER BY "employee_id", "department_id").
Some AGGREGATE Functions like STRING_AGG in bigquery allow collation without WITHIN_GROUP. i.e.,
STRING_AGG("first_name", ": " ORDER BY "employee_id", "department_id"). This MR add supports for that during Rel To Sql Conversion.

added support for STRING_AGG function with collation

---

core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
core/src/main/java/org/apache/calcite/util/Util.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

While translating a scenario where coalesce function was used on decimal field & replacement was given as string. raven translates its using PRINTF function but its not working on Databricks.

RTP_226_Conversion_Of_Coalesce

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

corrected mapping as per BigQuery Dialect
Select PARSE_DATETIME('%F %H:%M:%E.*S', CAST(CURRENT_DATETIME() AS STRING));
Select PARSE_DATETIME('%F %H:%M:%E*S', CAST(CURRENT_DATETIME() AS STRING));

replace format as per Bq

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Added column comment related changes.
If comment contains two consecutive single quote, it should be retained.
Also this occurred in Create table statement, we could not add relative test case for that method.

RSFB-1141: added column comment related changes

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java

RAVTDBQ-450: Support for INTERVAL_DAY, INTERVAL_HOUR, INTERVAL_MINUTE, and INTERVAL_MONTH data types in DDL.

RAVTDBQ-450: Support for INTERVAL Datatypes in DDL

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

This pull request introduces support for the edit_distance function in DM-Calcite, specifically tailored for the BigQuery SQL dialect. The edit_distance function calculates the Levenshtein edit distance between two strings, providing a valuable tool for string similarity analysis in BigQuery.
Changes:
Implemented the edit_distance function.
Ensured compatibility with the BigQuery SQL dialect.
Accompanied by unit tests to validate accuracy and functionality.

RAVTDBQ-576- function support for edit_distance

---

core/src/main/java/org/apache/calcite/tools/RelBuilder.java
core/src/test/java/org/apache/calcite/test/RelBuilderTest.java

Recently, we have encountered a new corner case related to Logical filters in our RelNodes. Specifically, when the filter condition is set to 1=2, the expression gets simplified, resulting in the filter always evaluating to false.
Upon thorough analysis, it has been identified that there is currently no configurable support for simplifying expressions in filters within Datamatica Calcite.
As support for the same was already added into calcite we just need to find changes and test-cases for the same and pulled into dm calcite.

Control simplification in "RelBuilder#filter" in calcite

---

core/src/main/java/org/apache/calcite/sql/SqlSelectOperator.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

Select query having "Qualify" keyword is failing when revisited using shuttle. 
Cause : createCall method in SqlSelectOperator is calling incorrect constructor of SqlSelect that does does not expect qualify in operandlist.

Sql select qualify support

---

core/src/main/java/org/apache/calcite/sql/SqlDateTimeFormat.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

Oracle supports Julian Date format, adding an enum value to make system parse the julian date format.

Julian enum support

---

core/src/test/java/org/apache/calcite/jdbc/CalciteRemoteDriverTest.java
core/src/test/java/org/apache/calcite/sql/test/SqlTypeNameTest.java

- Fixed TC failing due to CLOB datatype i.e. previously enabled

CLOB datatype

---

core/src/main/java/org/apache/calcite/sql/SqlIntervalQualifier.java
core/src/main/java/org/apache/calcite/sql/validate/AbstractNamespace.java
gradle.properties
linq4j/src/main/java/org/apache/calcite/linq4j/Nullness.java

Reverts datametica/calcite#614

Revert "updated the checker framework version"

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/sql/type/SqlDataTypeSpecTest.java

- Added adjustment on the precision to change it to 38 in BigQuerySqlDialect class if the datatype is BIGNUMERIC and precision is greater than 38

Handling for precision greater than 38 BIGNUMERIC  in BQ

---

core/src/main/java/org/apache/calcite/sql/dialect/PostgresqlSqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

Resolving extra t in case of concat in postgres procedure which was coming due to extra boolean Operand added to differentiate between CONCAT Operator(||) and CONCAT Function.

RSFB-3327/Concat2 Function Unparsing related changes

---

core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

removing UDF_REGEXP_INSTR from the UDF map as REGEXP_INSTR function is working in databricks

Nirnay.patil/raven/rmsss 204/support for patindex
