core/src/main/java/org/apache/calcite/sql/SqlDialectFactoryImpl.java
core/src/main/java/org/apache/calcite/sql/SqlKind.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlPositionFunction.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

POSITION,MOD & Set Operators emulation added.

[CALCITE-2623] Hive & BigQuery Sql Dialect

---

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

for Comparison operator explicit cast on string was getting removed.

Cast remove for string issue

---

core/src/main/java/org/apache/calcite/sql/SqlDialect.java
core/src/main/java/org/apache/calcite/sql/SqlKind.java
core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java

added format function support.

format function support

---

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
core/src/main/java/org/apache/calcite/sql/SqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Cast issue in comparison operator

---

core/src/main/java/org/apache/calcite/sql/SqlSelectOperator.java

Insert with select case:
- Group by has missing column names, where columnName is NULL.
Solution:
Don't add column in groupBy if columnName is NULL

Group by for NULL column issue fix

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Pull request to revert the trim changes from master

[Dhirenda Gautam]Reverting change of trim from master

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java

changed the return type for Format function to nullable type.

RAV-1221: changed the return type for Format function to nullable type.

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Code for handling trim function through canonical

[Dhirenda Gautam]Handling TRIM through canconical

---

core/src/main/java/org/apache/calcite/rex/RexSimplify.java
core/src/main/java/org/apache/calcite/sql/SqlKind.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

RAV-1200 : Handling for ascii method

RAV-1200 : Handling for ascii method

---

core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
core/src/main/java/org/apache/calcite/util/RelToSqlConverterUtil.java

Added a new class tool RelToSqlConverterUtil to have common code of ReltoSqlConverter

New common tool class for Common code

---

core/src/main/java/org/apache/calcite/sql/SqlDialectFactoryImpl.java
core/src/main/java/org/apache/calcite/sql/SqlKind.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
core/src/main/java/org/apache/calcite/util/ToNumberUtils.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
site/_docs/reference.md

RAV-1410 : Handling TO_NUMBER for snowflake

RAV-1410 : Handling TO_NUMBER for snowflake

---

core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java
core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlCollectionTableOperator.java
core/src/main/java/org/apache/calcite/tools/RelBuilder.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Changes done are referred from
https://github.com/apache/calcite/commit/50cfaec7c0e80eeee38caade997b7d473680cb9a

Table function scan support.

---

core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java

RAV-1410 : Override supportCharSet method in snowflake dialect

RAV-1410 : Override supportCharSet method in snowflake dialect

---

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
core/src/main/java/org/apache/calcite/sql/SqlDateTimeFormat.java
core/src/main/java/org/apache/calcite/sql/SqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/main/java/org/apache/calcite/sql/parser/CurrentTimestampHandler.java
core/src/main/java/org/apache/calcite/util/CastCallBuilder.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Handle Cast to Time & Timestamp in BQ, Hive, Spark

Handle cast function

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Support for character_length() and char_length()

Support for length has been added for snowflake

---

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/validate/SqlAbstractConformance.java
core/src/main/java/org/apache/calcite/sql/validate/SqlConformance.java
core/src/main/java/org/apache/calcite/sql/validate/SqlConformanceEnum.java
core/src/main/java/org/apache/calcite/sql/validate/SqlDelegatingConformance.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

added is true and is not true operator support.

added IS TRUE and IS NOT TRUE operator support.

---

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java

Added the handling for the IN/NOT IN support in the Join Clause and also added the OR handling in Inclause.

[RAV-1747]IN/NOT_IN not supported in JOIN

---

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Analytical Function In Group By Where Analytical Function Is Input Of Other Function

---

core/src/main/java/org/apache/calcite/rex/RexSimplify.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Support for coalesce function is added

coalesce function

---

core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Support of trim function for snowflake dialect has been added

support for trim function

---

core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Added IFF support in calcite for SnoFlake.

RAV-4085: Added IFF support in calcite

---

core/src/main/java/org/apache/calcite/sql/dialect/TeradataSqlDialect.java

RAV-3272 | Modifying TD source query in Cursor Statement in Raven-Proc using its rel and then Again relToSql.
Hence modifying for TD.

TD AliasedValues Method

---

core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

SINGLE_VALUE func in snowflake

---

core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Added FORMAT_DATE support

---

core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

- Log function support in snowflake

Log function support in snowflake

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Interval hour_to_second support for BQ

Interval hour_to_second support for BQ

---

core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Support for Divide_integer for snowflake which adds floor.

Divide_integer support for snowflake.

---

core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

- Added one more variation of OVER window for snowflake
- Revert POSITION from snowflake unparse

Handled variation of window function for snowflake

---

core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java
core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/main/java/org/apache/calcite/util/BuiltInMethod.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
core/src/test/java/org/apache/calcite/test/JdbcTest.java
core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java
site/_docs/reference.md

Added canonical support for INSTR.

INSTR canonical support

---

core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Added support for window frame requires order by and Round function support for Snowflake

Window frame and Round Function Support for Snowflake

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Random function support for Spark, Hive, BQ, and Snowflake which generates the random number between a specified range.

Random function Support for Spark, Hive, BQ And Snowflake

---

core/src/main/java/org/apache/calcite/sql/dialect/MssqlSqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibrary.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

RAV-4445-Trim-Support-For-MSSql

---

core/src/main/java/org/apache/calcite/sql/dialect/MssqlSqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

RAV-4557: CEIL to CEILING IN MSSQL

---

core/src/main/java/org/apache/calcite/sql/SqlDialect.java

System.out.println("type.getSqlTypeName() = " + type.getSqlTypeName().getName());

Commenting this line in SqlDialect

---

core/src/main/java/org/apache/calcite/rel/logical/RavenDistinctProject.java
core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java

Moved RavenDistinct project from mig to calcite and andded logic to make new rel for distict aggregate type of rel

Moved RavenDistinctProject class  from mig to calcite

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Add QUARTER mapping in QUARTER in DATE_TIME_FORMAT_MAP.

Add QUARTER in DATE_TIME_FORMAT_MAP.

---

core/src/main/java/org/apache/calcite/rel/rules/AggregateProjectMergeRule.java

…e have distinct and will not apply this merge rule on that

adding exception in aggregate project merge rule to ignore distinct inside logical aggregate

---

babel/src/test/resources/sql/redshift.iq
core/src/main/java/org/apache/calcite/sql/SqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

handled the unicode characters in the SQL Queries.

Unicode character handling.

---

core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

date minus

---

core/src/main/java/org/apache/calcite/sql/SqlDateTimeFormat.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Code changes corresponding to JIRA 8570
https://datametica.atlassian.net/browse/RAV-8570

Fixes Rav 8570

---

core/src/main/java/org/apache/calcite/rel/rules/FilterExtractInnerJoinRule.java

method of class FilterExtractInnerJoinRule

RAV-8108:Unsupported Subquery with table in join predicate

---

core/src/main/java/org/apache/calcite/sql/SqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/sql/type/SqlDataTypeSpecTest.java

SqlDataTypeSpecTest

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

https://datametica.atlassian.net/browse/RNBS-133

RNBS-133::Added support for NZ-BQ DATE_TRUNC/TIME_TRUNC

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Added support for TIME_TRUNC and DATETIME_TRUNC on BQ

RNBS-133-Adds-support-for-DATETIME_TRUNC_and_TIME_TRUNC

---

core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Format violation fixed by running " ./gradlew autostyleApply"

RNBS-140: Format violation fixed by running " ./gradlew autostyleApply"

---

core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlUtils.java
core/src/main/java/org/apache/calcite/sql/SqlSelect.java

RAV 9189 Add Qualify support for etl and starling tc fixed

RAV 9189 Add Qualify support for etl and starling tc fixed

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

https://datametica.atlassian.net/browse/RNBS-261

RNBS:261- UNIX_SECONDS for argument types: DATETIME

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

https://datametica.atlassian.net/browse/RNBS-800

RNS-800: Adds unparsing for Casting of [float value string] (eg: '45.34') to Integer in Bigquery

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Handled Interval with all possible combination .

Akshay khirolkar/raven rnbs 1051/virgin media/interval array index out of bounds exceptionwith 

---

core/src/main/java/org/apache/calcite/sql/SqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/main/java/org/apache/calcite/util/interval/SparkDateTimestampInterval.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Support for To_char With Trunc datatype mismatch.

Rtp 203 to char with trunc results in datatype mismatch

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/DateTimestampFormatUtil.java

Support for Native Hive Function - weekofyear

Shirinhasan/ravhibq 84/nativehivefunction weekofyear

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Added week of year in date time format map

---

core/src/main/java/org/apache/calcite/sql/SqlDialect.java
core/src/main/java/org/apache/calcite/sql/SqlWithItem.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/MssqlSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java

https://datametica.atlassian.net/browse/RNBS-1228

RNBS:1228 - WITH ITEM UNPARSING

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Added a case for Hour in unparseOtherFunction

Adding case for hour in unparseOtherFunction

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

1.added support for minute function and second function
2.for the same added test case for minute and second function.

RAVHIBQCAL-86(JIRA ID-RAVHIBQ-86)

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Adds changes to unparse COLUMN_LIST operator in BQ.

RNBS-1317-adds-unparsing-in-BQ-for-COLUMN_LIST

---

core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Re organized import statement to avoid format violations

Rushikesh.sapate/rtp 175 added next day function

---

core/src/main/java/org/apache/calcite/sql/SqlUpdate.java

https://datametica.atlassian.net/browse/RNBS-1053

RNBS-1053: SqlUpdate Unparsing

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

https://datametica.atlassian.net/browse/RNBS-593

Added DATETIME_DIFF in SqlLibraryOperators

---

core/src/main/java/org/apache/calcite/sql/SqlAbstractDateTimeLiteral.java
core/src/main/java/org/apache/calcite/sql/SqlLiteral.java
core/src/main/java/org/apache/calcite/sql/SqlTimestampWithTimezoneLiteral.java
core/src/main/java/org/apache/calcite/sql/parser/SqlParserUtil.java
core/src/main/java/org/apache/calcite/sql/type/SqlTypeName.java
core/src/test/java/org/apache/calcite/jdbc/CalciteRemoteDriverTest.java
core/src/test/java/org/apache/calcite/unparse/TimestampLiteralSqlNodeTest.java

Added support to create SqlNode for TIMESTAMP WITH TIME ZONE datatype.

RAVTDBQ-171 Support for Default Constraint

---

core/src/main/java/org/apache/calcite/sql/fun/SqlBetweenAsymmetricOperator.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java
core/src/main/java/org/apache/calcite/tools/RelBuilder.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

For Between Operator fix (RV-1848)

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

https://datametica.atlassian.net/browse/RORAB-243

Add SUBSTR4 Support for oracle

---

core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Mapped IFNULL to NVL in HIVE and added test case for the same

RAVTDBQ-275/ Mapped IFNULL to NVL in HIVE

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

RAVTDBQ_281_Support_For_Otranslate_Function

---

core/src/main/java/org/apache/calcite/sql/SqlAsOperator.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Reverts datametica/calcite#378

Revert "Shirinhasan/ravhibq 672/handling invalid escape sequences"

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Reverted earlier mapping of ASCII() from TO_CODE_POINTS() [OFFSET()] to ASCII()

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

RAVTDBQ_315_Support_For_CountSet

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

RAVTDBQ-318: Support for SETBIT function.

RAVTDBQ-318 : Support for SETBIT function.

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

https://datametica.atlassian.net/browse/RSFB-421

RSFB-421: Adds BigQuery CONCAT Function with multiple arguments

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

https://datametica.atlassian.net/browse/RSFB-417

regexp_instr function support

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

https://datametica.atlassian.net/browse/RSFB-535

DATE_DIFF function support for DATETIME Datatypes

---

piglet/src/main/java/org/apache/calcite/piglet/PigRelToSqlConverter.java

Later view autostyle correction

Autostyle check addressed

---

core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java
core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
piglet/src/main/java/org/apache/calcite/piglet/PigRelToSqlConverter.java
piglet/src/test/java/org/apache/calcite/test/PigRelOpTest.java

final code changes for RAVHIBQ-795 lateral view

Latest calcite changes for 795

---

core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java
core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
piglet/src/main/java/org/apache/calcite/piglet/PigRelToSqlConverter.java
piglet/src/test/java/org/apache/calcite/test/PigRelOpTest.java

Reverts datametica/calcite#406

Revert "Latest calcite changes for 795"

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

https://datametica.atlassian.net/browse/RSFB-510
https://datametica.atlassian.net/browse/RSFB-567

RSFB-510: Adds Bigquery TIMESTAMP function

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rex/RexBuilderTest.java
core/src/test/java/org/apache/calcite/test/SqlValidatorTest.java

https://datametica.atlassian.net/browse/RSFB-574

TO_TIMESTAMP function definition changes.

---

core/src/main/java/org/apache/calcite/sql/fun/SqlStdOperatorTable.java
core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java
core/src/test/java/org/apache/calcite/sql/test/SqlOperatorBaseTest.java

modification in acos,asin,atan and sqrt function defition for using safe cast at bigquery

modification in acos,asin,atan and sqrt function defition

---

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Handling of classcastexception: SqlIdentifier to SqlBasicCall
hadling of definition of Oracle_next_day Function

handled classcast exception from sqlIdentifier to SqlbasicCall.

---

core/src/main/java/org/apache/calcite/tools/RelBuilder.java
core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml

Flipkart : Fixed COALESCE() is getting removed

RAVHIBQ-733 Flipkart : Fixed COALESCE() is getting removed

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

https://datametica.atlassian.net/browse/RSFB-575

RSFB-575: Adds Bigquery TRY_TO_DATE function

---

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Reverts datametica/calcite#432

Revert "Shirinhasan/ravhibq 867/case clause in aggregate functions/cast exceptions"

---

core/src/main/java/org/apache/calcite/sql/type/BasicSqlType.java
core/src/test/java/org/apache/calcite/sql/type/SqlTypeFactoryTest.java

Datatype cache to handle decimal datatype without precision

Adding max numeric value to decimal dataype for cahce

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Added TO_HEX function in SqlLibraryOperators

RSFB-1391: added TO_HEX function in SqlLibraryOperators

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

function defination for parse_json

Added Function defination for parse_json

---

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
core/src/main/java/org/apache/calcite/rel/rules/AggregateProjectPullUpConstantsRule.java
core/src/main/java/org/apache/calcite/rel/rules/ReduceExpressionsRule.java
core/src/main/java/org/apache/calcite/rel/rules/ValuesReduceRule.java
core/src/main/java/org/apache/calcite/rex/RexBuilder.java
core/src/main/java/org/apache/calcite/rex/RexCall.java
core/src/main/java/org/apache/calcite/rex/RexCallBinding.java
core/src/main/java/org/apache/calcite/rex/RexUtil.java
core/src/main/java/org/apache/calcite/sql/SqlDialect.java
core/src/main/java/org/apache/calcite/sql/SqlKind.java
core/src/main/java/org/apache/calcite/sql/SqlSplittableAggFunction.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/HiveSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlCastFunction.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/plan/RelOptUtilTest.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
core/src/test/java/org/apache/calcite/rex/RexProgramBuilderBase.java

Reverts datametica/calcite#454

Revert "Add support for SAFE_CAST"

---

core/src/main/java/org/apache/calcite/rel/rules/FilterCorrelateRule.java
core/src/test/java/org/apache/calcite/test/SqlToRelConverterTest.java
core/src/test/resources/org/apache/calcite/test/SqlToRelConverterTest.xml

Wrong translation of later view explode, update rule for same

Ravhibq 861

---

core/src/main/java/org/apache/calcite/rel/rules/FilterExtractInnerJoinRule.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

ClassCastException in  FilterExtractInnerJoinRule fix

---

.idea/vcs.xml
core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java

$cor Variable handling for Project and Filter clause in case of alias clause.

Saurabh.ajmera/ravtdbq 353 cor variable issue inside projection and filter

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

handling CURRENT_TIMESTAMP() in DATEADD

Handled current_timestamp() in DATEADD With DATETIME_ADD

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java

Reverts datametica/calcite#516

Revert "RSFB:2082 - Adds one more oparand to SPLIT function"

---

core/src/main/java/org/apache/calcite/sql/SqlKind.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/ClickHouseSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/JethroDataSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/MssqlSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SnowflakeSqlDialect.java
core/src/main/java/org/apache/calcite/sql/dialect/SparkSqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java
core/src/test/java/org/apache/calcite/sql/parser/SqlParserTest.java

This PR is only for the dialect sub-package.

RAVCOM-444_Upgrade_Core_Module_Sql_Package

---

core/src/main/java/org/apache/calcite/plan/CTEDefinationTrait.java
core/src/main/java/org/apache/calcite/plan/CTEDefinationTraitDef.java
core/src/main/java/org/apache/calcite/plan/CTEScopeTrait.java
core/src/main/java/org/apache/calcite/plan/CTEScopeTraitDef.java
core/src/main/java/org/apache/calcite/rel/rel2sql/CTERelToSqlUtil.java
core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java
core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

RAVHIBQ-927 : Nested CTE Implementation for views

RAVHIBQ-927 : Nested CTE Implementation for views

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Reverts datametica/calcite#547

Revert "Trunc function fix for single operand"

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterTest.java

Regexp_Replace_With_Null_Argument

RAVTDBQ_366_Regexp_Replace_With_Null_Argument

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

adds support for div0 as operator

RSFB-2638: adds support for DIV0 operator

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

RSFB-2507 Regexp contains unparsing fixed

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/main/java/org/apache/calcite/sql/type/ReturnTypes.java
core/src/main/java/org/apache/calcite/sql/type/SqlTypeName.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

Added function support for TO_CLOB function.
Enabled CLOB datatype.

TO_CLOB function support.

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java

Addition of BIG_QUERY for the SqlFunction MD5

Addition of BIG_QUERY for the SqlFunction MD5

---

core/src/main/java/org/apache/calcite/rel/rules/FilterCorrelateRule.java
core/src/main/java/org/apache/calcite/sql2rel/RelDecorrelator.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

variable not found issue in correlated exists query

---

core/src/main/java/org/apache/calcite/sql/fun/SqlAddMonths.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

Changing the logic of ADD_MONTHS

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibrary.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

Reverts datametica/calcite#583

Revert "Added support for DB2 DAYS_BETWEEN function"

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

Reverts datametica/calcite#587

Revert "Added support Last_day function"

---

core/src/main/java/org/apache/calcite/sql/SqlIntervalQualifier.java
core/src/main/java/org/apache/calcite/sql/validate/AbstractNamespace.java
gradle.properties
linq4j/src/main/java/org/apache/calcite/linq4j/Nullness.java

checker framework version update

checker framework version update

---

core/src/main/java/org/apache/calcite/plan/QualifyRelTrait.java
core/src/main/java/org/apache/calcite/plan/QualifyRelTraitDef.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

introducing Reltrain for Qualify.

---

core/src/main/java/org/apache/calcite/sql/SqlDateTimeFormat.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/main/java/org/apache/calcite/sql/type/OperandTypes.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

Added support for mentioned date formats and changed operand types of PARSE_TIMESTAMP_WITH_TIMEZONE function as it can accept other datatypes also

Added support for ddmmyyyyhh24 and yymmddhh24miss formats

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/main/java/org/apache/calcite/util/CastCallBuilder.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

Function support for EXTRACT2 which is exactly similar to CAST(EXTRACT as FLOAT64)

Rushikesh.sapate/prgb 10/function support for extract2

---

core/src/main/java/org/apache/calcite/plan/InnerJoinTrait.java
core/src/main/java/org/apache/calcite/plan/InnerJoinTraitDef.java
core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java
core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlUtils.java

Fixed ROP-87 ORA-PY Support for Select with join : Added traits in REL

Fixed ROP-87 ORA-PY Support for Select with join

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

https://datametica.atlassian.net/browse/RSFB-3316

PARSE_IP SqlFunction support

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/sql/type/SqlDataTypeSpecTest.java

Fix for scale above precision 38

Fix for scale above precision 38

---

core/src/main/java/org/apache/calcite/plan/ViewChildProjectRelTrait.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

998- timestamp with timezone with view derived from view

998- timestamp with timezone with view derived from view

---

core/src/main/java/org/apache/calcite/sql/type/SqlTypeName.java
core/src/main/java/org/apache/calcite/sql/type/SqlTypeUtil.java
core/src/test/java/org/apache/calcite/jdbc/CalciteRemoteDriverTest.java
core/src/test/java/org/apache/calcite/sql/type/SqlTypeFixture.java
core/src/test/java/org/apache/calcite/sql/type/SqlTypeUtilTest.java

support for interval datatype

---

core/src/main/java/org/apache/calcite/plan/ViewChildProjectRelTrait.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

Reverts datametica/calcite#705

Revert "998- timestamp with timezone with view derived from view"

---

core/src/main/java/org/apache/calcite/rel/rel2sql/RelToSqlConverter.java

…s aggregate function and QUALIFY uses CASE expression

Resolve alias when case expr contains aggregate used in qualify

---

core/src/main/java/org/apache/calcite/sql/SqlMerge.java
core/src/main/java/org/apache/calcite/sql/SqlMergeWithCte.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java

https://datametica.atlassian.net/browse/RSFB-3424

RSFB-3424: SqlNode SqlMergeWithCte unparsing

---

core/build.gradle.kts

Log calcite-core module exception

Add plugin for Aspect

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

Support for CASE expression in TO_TIMESTAMP function

PRGB-43  Support for CASE expression in TO_TIMESTAMP function

---

core/src/main/java/org/apache/calcite/plan/ViewChildProjectRelTrait.java
core/src/test/java/org/apache/calcite/jdbc/CalciteRemoteDriverTest.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

RTB - 1075 - Timestamp with timezone insert from view.

RTB - 1075 - Timestamp with timezone for insert statement from view.

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

-Added support for DATETRUNC function in MS SQL SERVER

RMSB-64 :Support for DATETRUNC function in MS SQL SERVER

---

core/src/main/java/org/apache/calcite/sql/dialect/PostgresqlSqlDialect.java
core/src/main/java/org/apache/calcite/sql/type/SqlTypeName.java
core/src/test/java/org/apache/calcite/jdbc/CalciteRemoteDriverTest.java

Raven: PostgreSql datatype handling

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibrary.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

Refactor Handling of POWER Function.

RMSB-106 : Refactor Handling of POWER Function.

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

https://datametica.atlassian.net/browse/RSFB-3616

added JOSN_EXTRACT_ARRAY function in SqlLibraryOperators

---

core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

http://taiga.datametica.com/migrations/mig-v2/-/merge_requests/17255

rsfb-3768-standardize rex in simpleObjectNameRexBuilder

---

core/src/main/java/org/apache/calcite/sql/SqlUpdate.java

https://datametica.atlassian.net/browse/RMSB-23

SqlKindSourceCollectorMap for Select Stmt

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java

https://datametica.atlassian.net/browse/RPB-124

IDENTIFIER is not valid fixed

---

core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

added support for MINUS inside INTERVAL

support with the insertion of Julian Date 'YYDDD'

---

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

In filter clause has filed and checking if it is alias and alias name has same name as field name then checked it on object base

same name alias issue handling in filter qualify clause

---

core/src/main/java/org/apache/calcite/rel/rel2sql/SqlImplementor.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

Revert "same name alias issue handling in filter qualify clause"

---

core/src/main/java/org/apache/calcite/sql/SqlDateTimeFormat.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

added support for QQYY and QQYYYY

added support for QQYY

---

core/src/main/java/org/apache/calcite/rex/RexWindow.java

RTB-1972 : adding accept in RexWindow

---

core/src/main/java/org/apache/calcite/plan/RelOptUtil.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

Handling of column ambiguity due to subquery in join

Handling of column ambiguity due to subquery in join

---

core/src/main/java/org/apache/calcite/sql/SqlKind.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

added function array_unique_agg()

---

core/src/main/java/org/apache/calcite/rel/rel2sql/CTERelToSqlUtil.java
core/src/main/java/org/apache/calcite/sql/dialect/BigQuerySqlDialect.java
core/src/main/java/org/apache/calcite/sql/fun/SqlLibraryOperators.java
core/src/test/java/org/apache/calcite/rel/rel2sql/RelToSqlConverterDMTest.java

Added Support for SNOWFLAKE_REGEXP_LIKE and CTE inside CASE WHEN and Removing Extra CTE'S added

RSFB-3763 and RSFB-3951 Fix.
